config/routes.rb
Rails.application.routes.draw do
  resources :notes
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "notes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
  has_rich_text :content
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @notes = Note.all
  end

  def show

  end

  def new
    @note = current_user.notes.build
  end

  def create
    @note = current_user.notes.build(note_params)
    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was created successfully." }
      else
        format.html { render :new, status: :unprocessable_entity}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @note.destroy
    respond_to do |format|
        format.html { redirect_to notes_url(@note), notice: "Note was successfully deleted." }
    end
  end

  private
  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :content, :user_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p
      <header>
        <navbar>
          <% if user_signed_in? %>
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %>
            <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </navbar>
        <h1> Note Taking Application</h1>
      </header>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <div class="">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>


<div class="">
  <%= form.hidden_field :user_id, value: current_user.id %>
</div>

  <div class="">
    <%= form.submit %>
  </div>

<% end %>

app/views/notes/_note.html.erb
<div id="<%= dom_id note %>">
  <p><%= note.title %></p>
  <p><%= note.content %></p>

</div>

app/views/notes/edit.html.erb
<h1> Edit Note </h1>

<%= render "form", note: @note %>

app/views/notes/index.html.erb
<h1> Notes </h1>

  <%= render @notes %>

<%= link_to "Create Note", new_note_path %>

app/views/notes/new.html.erb
<h1> Create new note </h1>

<%= render "form", note: @note %>

app/views/notes/show.html.erb
<h1> Note </h1>

<%= render @note %>

<%= button_to "Delete this note", note_path(@note), method: :delete %>

<%= link_to "New Note", new_note_path %>
<%= link_to "Show All Notes", notes_path %>